version: '3'

services:
    nginx:
        image: myweb-nginx:v1
        build: ./nginx
        volumes:
            - ./src/web:/var/www/html
        ports:
            - 80:80
        depends_on:
            - php-fpm

    php-fpm:
        image: myweb-php-fpm:v1
        build: ./php-fpm
        volumes:
            - ./src/web:/var/www/html
